### ISSUE TITLE
Another paper not included

### ISSUE THREAD

**Issue by ricbl** [JunMa11/MICCAI2019-OpenSourcePapers#7]
Hi,

This is my paper from last year's MICCAI with open source code for part of the experiments: 
Title: Adversarial regression training for visualizing the progression of chronic obstructive pulmonary disease with chest x-rays
Github Link: https://github.com/ricbl/vrgan
Link to paper: doi.org/10.1007/978-3-030-32226-7_76

Thanks

**Comment by JunMa11** [comment]
Hi @ricbl ，

Thanks for sharing.
I have added it.
